
let guiData = {
    w: 2.0, h: 2.0,
    bx: 0.5, by: 0.5, px: 0.0, py: 40.0,
    initMomentumByPxPySliders: false,
    dt: 0.00001,
    // dt: 0.001,
    sigma: 0.05859375,
    // The fundamental constants used are expressed
    // in terms of [Hartree atomic units]
    // (https://en.wikipedia.org/wiki/Hartree_atomic_units)
    m: 1.0, c: 137.036, hbar: 1.0,
    t: 0.0,
    drawShape: 'circle',
    drawSize: 0.01,
    drawValue: 10000/137.036,
    mouseSelect: 'New ψ(x, y)',
    presetPotentials: 'Free (Periodic)',
    useVectorPotential: false,
    presetVectorPotentials: 'None',
    potentialType: 7,
    stepsPerFrame: 6,
    brightness: 1.0,
    applyPhaseShift: true,
    showFPS: false, timeMilliseconds: 0,
    showPsi1: true, showPsi2: true, showPsi3: true, showPsi4: true,
    isDisplayUpdate: true,
    phaseOption: 'ψ1 Phase',
    phaseOptions: ['ψ1 Phase', 'ψ2 Phase', 'ψ3 Phase', 'ψ4 Phase', 
                   '|ψ12|-|ψ34|', 'None'],
    phaseMode: 0,
    showWavefuncHeightMap: false,
    showPotentialHeightMap: false,
    potentialDisplayMode: 0,
    mouseAction: false,
    mouseCount: 0,
    reshapePotentialRecursionLevel: 0,
    presetPotentialSettings: {"a": 10000.0/137.036, "y0": 0.45, "w": 0.02, 
                              "spacing": 0.03, "x1": 0.43, "x2": 0.57},
    measurePosition: e => {},
    drawRect: {x: 0.0, y: 0.0, w: 0.0, h: 0.0},
    probInRegion: '0',
    showBox: false,
    viewProbCurrent: false,
    probColour: [1.0, 1.0, 1.0],
    potBrightness: 1.0,
    potColour: [1.0, 1.0, 1.0],
    gridDimensions: '512x512',
    imageName: '',
    imageFunc: () => {},
    screenshots: [],
    screenshotNames: [],
    screenshotCount: 0,
    nScreenshots: 1,
    takeScreenshot: false,
    setStartSpeed: false,
    startSpeed: 1,
    screenshotProgress: '',
    pauseOnFinish: false

};

